install.packages('ibmdbR')  
install.packages('tidyverse')
library(ibmdbR)
library('timeDate')
library('lubridate')
library('tidyverse')

#Credentials and connect to Dashdb
dsn_driver <- "BLUDB"  
dsn_database <- "BLUDB"   
dsn_hostname <- "dashdb-entry-yp-dal09-08.services.dal.bluemix.net"  
dsn_port <- "50000"  
dsn_protocol <- "TCPIP"  
dsn_uid <- "dash8666"  
dsn_pwd <- "5c74a7ed2ecb" 

conn_path <- paste(dsn_driver,  
                   ";DATABASE=",dsn_database,
                   ";HOSTNAME=",dsn_hostname,
                   ";PORT=",dsn_port,
                   ";PROTOCOL=",dsn_protocol,
                   ";UID=",dsn_uid,
                   ";PWD=",dsn_pwd,sep="")

ch <- idaConnect(conn_path)  
idaInit(ch)  


#Create in database pointers
CUSTOMER_TABLE_FINAL = ida.data.frame('CUSTOMER_TABLE_FINAL')
CUSTOMER_INVOICE_JOURNAL = ida.data.frame('CUSTOMER_INVOICE_JOURNAL')
CUST_INVOICE_TRANS = ida.data.frame('CUST_INVOICE_TRANS')

#Join Customer Table and INVOICE journal in DASHDB (makes database do heavy lifting)
#idadf_CUSTOMER_INVOICE_JOURNAL <- idaMerge(INVOICE_JOURNAL,CUSTOMER_TABLE_FINAL,by="CUSTOMER_ACCOUNT",all.x=TRUE,all.y=FALSE)

#Change ida data froms to R frames
R_CUSTOMER_INVOICE_JOURNAL <- as.data.frame(CUSTOMER_INVOICE_JOURNAL)
R_CUST_INVOICE_TRANS <- as.data.frame(CUST_INVOICE_TRANS)
R_CUSTOMER_TABLE_FINAL = as.data.frame(CUSTOMER_TABLE_FINAL)

#Set variables to correct data type

#R_CUST_INVOICE_TRANS
R_CUST_INVOICE_TRANS$COGS = as.numeric(R_CUST_INVOICE_TRANS$COGS)
R_CUST_INVOICE_TRANS$LINE_AMT_PRE_DISCOUNT = as.numeric(R_CUST_INVOICE_TRANS$LINE_AMT_PRE_DISCOUNT)
R_CUST_INVOICE_TRANS$LINE_AMT_POST_DISCOUNT = as.numeric(R_CUST_INVOICE_TRANS$LINE_AMT_POST_DISCOUNT)
R_CUST_INVOICE_TRANS$INVOICED_DISCOUNT_ACY = as.numeric(R_CUST_INVOICE_TRANS$INVOICED_DISCOUNT_ACY)
R_CUST_INVOICE_TRANS$SALES_PRICE = as.numeric(R_CUST_INVOICE_TRANS$SALES_PRICE)

#R_CUSTOMER_INVOICE_JOURNAL
R_CUSTOMER_INVOICE_JOURNAL$INVOICE_DATE = as.Date(R_CUSTOMER_INVOICE_JOURNAL$INVOICE_DATE,format='%Y-%m-%d')
R_CUSTOMER_INVOICE_JOURNAL$INVOICE_AMOUNT = as.numeric(R_CUSTOMER_INVOICE_JOURNAL$INVOICE_AMOUNT)
R_CUSTOMER_INVOICE_JOURNAL$CASH_DIS_VALUE = as.numeric(R_CUSTOMER_INVOICE_JOURNAL$CASH_DIS_VALUE)
R_CUSTOMER_INVOICE_JOURNAL$LINE_DISCOUNT = as.numeric(R_CUSTOMER_INVOICE_JOURNAL$LINE_DISCOUNT)
R_CUSTOMER_INVOICE_JOURNAL$SALES_SUBTOTAL_AMOUNT = as.numeric(R_CUSTOMER_INVOICE_JOURNAL$SALES_SUBTOTAL_AMOUNT)
R_CUSTOMER_INVOICE_JOURNAL$INVOICE_AMOUNT_AC = as.numeric(R_CUSTOMER_INVOICE_JOURNAL$INVOICE_AMOUNT_AC)
R_CUSTOMER_INVOICE_JOURNAL$LINE_DISCOUNT_AC = as.numeric(R_CUSTOMER_INVOICE_JOURNAL$LINE_DISCOUNT_AC)
R_CUSTOMER_INVOICE_JOURNAL$SALES_SUBTOTAL_AMOUNT_AC = as.numeric(R_CUSTOMER_INVOICE_JOURNAL$SALES_SUBTOTAL_AMOUNT_AC)
R_CUSTOMER_INVOICE_JOURNAL$CHARGES_AC = as.numeric(R_CUSTOMER_INVOICE_JOURNAL$CHARGES_AC)
R_CUSTOMER_INVOICE_JOURNAL$CHARGES = as.numeric(R_CUSTOMER_INVOICE_JOURNAL$CHARGES)

#R_CUSTOMER_TABLE_FINAL
R_CUSTOMER_TABLE_FINAL$CUR_CREDIT_LIMIT = as.numeric(R_CUSTOMER_TABLE_FINAL$CUR_CREDIT_LIMIT)
R_CUSTOMER_TABLE_FINAL$CREDIT_LIMIT = as.numeric(R_CUSTOMER_TABLE_FINAL$CREDIT_LIMIT)

#Tag free text journal entries as 1 and everything else as 0
R_CUSTOMER_INVOICE_JOURNAL$JOURNAL_TF <- ifelse(R_CUSTOMER_INVOICE_JOURNAL$ORDER_TYPE == 'Journal',1, 0)

#Split the dataframe so free text journal entries have its own dataframe
INVOICE_JOURNAL_TABLE_LIST <- split(R_CUSTOMER_INVOICE_JOURNAL, R_CUSTOMER_INVOICE_JOURNAL$JOURNAL_TF)
R_CUSTOMER_INVOICE_JOURNAL <- INVOICE_JOURNAL_TABLE_LIST[[1]]
R_CUSTOMER_FREE_TEXT_INVOICE_JOURNAL <- INVOICE_JOURNAL_TABLE_LIST[[2]] 

#Create Year,month and day columns in CUSTOMER INVOICE JOURNAL
R_CUSTOMER_INVOICE_JOURNAL <- transform(R_CUSTOMER_INVOICE_JOURNAL,YEAR_INVOICE=year(INVOICE_DATE),MONTH_INVOICE=month(INVOICE_DATE))

#Sum quantity and COGs per invoice then join it to the INVOICE JOURNAL
R_CUST_INVOICE_TRANS_SUM <- ddply(R_CUST_INVOICE_TRANS,"DOCUMENT_NUMBER__INVOICE_ID_",summarise,INVOICE_QUANTITY = sum(INVOICED_QTY, na.rm=TRUE),COGS2=sum(COGS, na.rm=TRUE))

#Join the quantity and COGS columns to the CUSTOMER_INVOICE_JOURNAL
R_CUSTOMER_INVOICE_JOURNAL <- merge(R_CUSTOMER_INVOICE_JOURNAL,R_CUST_INVOICE_TRANS_SUM,by.x="INVOICE_NUMBER",by.y="DOCUMENT_NUMBER__INVOICE_ID_",all.x=TRUE,all.y=FALSE)

#Join VAS and EDI codes to the customer invoice journal
R_CUSTOMER_INVOICE_JOURNAL <- merge(R_CUSTOMER_INVOICE_JOURNAL,R_CUSTOMER_TABLE_FINAL[,c("CUSTOMER_ACCOUNT","VAS_CODES_GROUP","EDI_CODE")],by="CUSTOMER_ACCOUNT",all.x=TRUE,all.y=FALSE)

#Create inventory management and freight cost columns
R_CUSTOMER_INVOICE_JOURNAL <- transform(R_CUSTOMER_INVOICE_JOURNAL,FREIGHT_COST= ifelse(R_CUSTOMER_INVOICE_JOURNAL$ORDER_TYPE == 'Sales order',0.7*INVOICE_QUANTITY,0),PICKING_COST=ifelse(R_CUSTOMER_INVOICE_JOURNAL$ORDER_TYPE == 'Sales order',0.06*INVOICE_QUANTITY,0),GENERAL_DISPATCH_COSTS=ifelse(R_CUSTOMER_INVOICE_JOURNAL$ORDER_TYPE == 'Sales order',0.64*INVOICE_QUANTITY,0),STORAGE_COSTS=ifelse(R_CUSTOMER_INVOICE_JOURNAL$ORDER_TYPE == 'Sales order',0.5*INVOICE_QUANTITY,0),VAS_COSTS = ifelse(!is.na(R_CUSTOMER_INVOICE_JOURNAL$VAS_CODES_GROUP) & R_CUSTOMER_INVOICE_JOURNAL$ORDER_TYPE == 'Sales order',0.16*INVOICE_QUANTITY,0),PACKAGING_CHARGE=ifelse(R_CUSTOMER_INVOICE_JOURNAL$ORDER_TYPE == 'Sales order',0.089*INVOICE_QUANTITY,0))
head(R_CUSTOMER_INVOICE_JOURNAL)

#Create Customer service cost column
R_CUSTOMER_INVOICE_JOURNAL <- transform(R_CUSTOMER_INVOICE_JOURNAL,CUSTOMER_SERVICE_COST = ifelse(R_CUSTOMER_INVOICE_JOURNAL$ORDER_TYPE == 'Sales order',ifelse(!is.na(R_CUSTOMER_INVOICE_JOURNAL$EDI_CODE), 0.083*14.5, 0.5*14.5),0))
head(R_CUSTOMER_INVOICE_JOURNAL)

#Create IT (per transaction) cost column
R_CUSTOMER_INVOICE_JOURNAL <- transform(R_CUSTOMER_INVOICE_JOURNAL, IT_COST_TRANS = ifelse(R_CUSTOMER_INVOICE_JOURNAL$ORDER_TYPE == 'Sales order',0.12,0))


# New version of length which can handle NA's: if na.rm==T, don't count them
length2 <- function (x, na.rm=TRUE) {
  if (na.rm) sum(!is.na(x))
  else       length(x)
}
#Create counts and sums of numeric values from invoice table by customer_account including counts of invoices and sales orders
INVOICE_SUMS <- ddply(R_CUSTOMER_INVOICE_JOURNAL,.(YEAR_INVOICE, MONTH_INVOICE, CUSTOMER_ACCOUNT),summarise,SALES_SUBTOTAL_AMOUNT_AC = sum(SALES_SUBTOTAL_AMOUNT_AC, na.rm=TRUE),LINE_DISCOUNT_AC=sum(LINE_DISCOUNT_AC, na.rm=TRUE),CHARGES_AC = sum(CHARGES_AC, na.rm=TRUE),INVOICE_SALES_ORDER=length2(which(ORDER_TYPE=='Sales order')),INVOICE_RETURNED_ORDER=length2(which(ORDER_TYPE=='Returned order')),SALES_ORDER_COUNT=length2(unique(SALES_ORDER)),COGS=sum(COGS2, na.rm=TRUE),FREIGHT_COST=sum(FREIGHT_COST),PICKING_COST=sum(PICKING_COST),GENERAL_DISPATCH_COSTS = sum(GENERAL_DISPATCH_COSTS),STORAGE_COSTS=sum(STORAGE_COSTS),VAS_COSTS=sum(VAS_COSTS),PACKAGING_CHARGE=sum(PACKAGING_CHARGE),CUSTOMER_SERVICE_COST=sum(CUSTOMER_SERVICE_COST),IT_COST_TRANS=sum(IT_COST_TRANS))   

#Add those counts/sums created to the customer table
R_CUSTOMER_TABLE_FINAL <- merge(INVOICE_SUMS,R_CUSTOMER_TABLE_FINAL,by="CUSTOMER_ACCOUNT",all.x=TRUE,all.y=FALSE)
head(R_CUSTOMER_TABLE_FINAL)
#Add the free text invoices into the customer level view
R_CUSTOMER_FREE_TEXT_INVOICE_JOURNAL <- transform(R_CUSTOMER_FREE_TEXT_INVOICE_JOURNAL,MONTH_INVOICE=month(INVOICE_DATE),YEAR_INVOICE=year(INVOICE_DATE))
R_CUSTOMER_FREE_TEXT_INVOICE_JOURNAL_SUMS <- ddply(R_CUSTOMER_FREE_TEXT_INVOICE_JOURNAL,.(YEAR_INVOICE,MONTH_INVOICE,CUSTOMER_ACCOUNT),summarise,MANUAL_DISCOUNT = sum(SALES_SUBTOTAL_AMOUNT_AC))


R_CUSTOMER_TABLE_FINAL <- merge(R_CUSTOMER_TABLE_FINAL,R_CUSTOMER_FREE_TEXT_INVOICE_JOURNAL_SUMS,by=c("MONTH_INVOICE","CUSTOMER_ACCOUNT"),all.x=TRUE,all.y=TRUE)

R_CUSTOMER_TABLE_FINAL <- transform(R_CUSTOMER_TABLE_FINAL,PROFIT = SALES_SUBTOTAL_AMOUNT_AC - COGS - FREIGHT_COST - PICKING_COST - GENERAL_DISPATCH_COSTS - STORAGE_COSTS - VAS_COSTS - PACKAGING_CHARGE - CUSTOMER_SERVICE_COST - IT_COST_TRANS )
head(R_CUSTOMER_TABLE_FINAL)
R_CUSTOMER_TABLE_FINAL <- ddply(R_CUSTOMER_TABLE_FINAL,"CUSTOMER_ACCOUNT",summarise,PROFIT = sum(PROFIT))