rm(list = ls()) # clear the workspace as precaution
setwd("C:/Users/rp/Projects/Icebreaker_rp")

#install.packages('ibmdbR')  
#install.packages('tidyverse')
#install.packages('NbClust')
library('ibmdbR')
#library('timeDate')
library('lubridate')
library('tidyverse')
library('NbClust')

library('e1071')
require(plyr)
#install.packages('e1071')  

#Credentials and connect to Dashdb
dsn_driver <- "dashdb"  # BLUDB
dsn_database <- "BLUDB"   
dsn_hostname <- "dashdb-entry-yp-dal09-08.services.dal.bluemix.net"  
dsn_port <- "50000"  
dsn_protocol <- "TCPIP"  
dsn_uid <- "dash8666"  

dsn_pwd <- "5c74a7ed2ecb" 
 
conn_path <- paste(dsn_driver,  
      ";DATABASE=",dsn_database,
      ";HOSTNAME=",dsn_hostname,
      ";PORT=",dsn_port,
      ";PROTOCOL=",dsn_protocol,
      ";UID=",dsn_uid,
      ";PWD=",dsn_pwd,sep="")
 
ch <- idaConnect(conn_path)  
idaInit(ch)  


#Create in database pointers
CUSTOMER_TABLE_FINAL = ida.data.frame('CUSTOMER_TABLE_FINAL')
CUSTOMER_INVOICE_JOURNAL = ida.data.frame('CUSTOMER_INVOICE_JOURNAL')
CUST_INVOICE_TRANS = ida.data.frame('CUST_INVOICE_TRANS')
RETURN_REASON_CODES = ida.data.frame('RETURN_REASON_CODES')
WAREHOUSING_COSTS = ida.data.frame('WAREHOUSING_COSTS')

#Join Customer Table and INVOICE journal in DASHDB (makes database do heavy lifting)
#idadf_CUSTOMER_INVOICE_JOURNAL <- idaMerge(INVOICE_JOURNAL,CUSTOMER_TABLE_FINAL,by="CUSTOMER_ACCOUNT",all.x=TRUE,all.y=FALSE)

#Change ida data froms to R frames
R_CUSTOMER_INVOICE_JOURNAL <- as.data.frame(CUSTOMER_INVOICE_JOURNAL)
R_CUST_INVOICE_TRANS <- as.data.frame(CUST_INVOICE_TRANS)
R_CUSTOMER_TABLE_FINAL = as.data.frame(CUSTOMER_TABLE_FINAL)
R_RETURN_REASON_CODES = as.data.frame(RETURN_REASON_CODES)
R_WAREHOUSING_COSTS = as.data.frame(WAREHOUSING_COSTS)


#Set variables to correct data type
#R_WAREHOUSING_COSTS
R_WAREHOUSING_COSTS$PICKING_PU = as.numeric(R_WAREHOUSING_COSTS$PICKING_PU)
R_WAREHOUSING_COSTS$DISPATCH_PU= as.numeric(R_WAREHOUSING_COSTS$DISPATCH_PU)
R_WAREHOUSING_COSTS$VAS_PU = as.numeric(R_WAREHOUSING_COSTS$VAS_PU)
R_WAREHOUSING_COSTS$PACKAGING_PU = as.numeric(R_WAREHOUSING_COSTS$PACKAGING_PU)
R_WAREHOUSING_COSTS$WAREHOUSING_COSTS_PU = as.numeric(R_WAREHOUSING_COSTS$WAREHOUSING_COSTS_PU)
R_WAREHOUSING_COSTS$RETURNS_PU = as.numeric(R_WAREHOUSING_COSTS$RETURNS_PU)
R_WAREHOUSING_COSTS$FREIGHT_COSTS_PU = as.numeric(R_WAREHOUSING_COSTS$FREIGHT_COSTS_PU)
R_WAREHOUSING_COSTS$SALES_ORDER_PROCESSING_PH = as.numeric(R_WAREHOUSING_COSTS$SALES_ORDER_PROCESSING_PH)
R_WAREHOUSING_COSTS$RETURN_ORDER_PROCESSING_PH = as.numeric(R_WAREHOUSING_COSTS$RETURN_ORDER_PROCESSING_PH)
R_WAREHOUSING_COSTS$FINANCE_PH= as.numeric(R_WAREHOUSING_COSTS$FINANCE_PH)
R_WAREHOUSING_COSTS$EDI_TRANSACTION_COSTS = as.numeric(R_WAREHOUSING_COSTS$EDI_TRANSACTION_COSTS)
R_WAREHOUSING_COSTS$THREE_P_FIVE_FIXED_COST = as.numeric(R_WAREHOUSING_COSTS$THREE_P_FIVE_FIXED_COST)
R_WAREHOUSING_COSTS$CS_FIXED_COST = as.numeric(R_WAREHOUSING_COSTS$CS_FIXED_COST)

#R_CUST_INVOICE_TRANS
R_CUST_INVOICE_TRANS$COGS = as.numeric(R_CUST_INVOICE_TRANS$COGS)
R_CUST_INVOICE_TRANS$LINE_AMT_PRE_DISCOUNT = as.numeric(R_CUST_INVOICE_TRANS$LINE_AMT_PRE_DISCOUNT)
R_CUST_INVOICE_TRANS$LINE_AMT_POST_DISCOUNT = as.numeric(R_CUST_INVOICE_TRANS$LINE_AMT_POST_DISCOUNT)
R_CUST_INVOICE_TRANS$INVOICED_DISCOUNT_ACY = as.numeric(R_CUST_INVOICE_TRANS$INVOICED_DISCOUNT_ACY)
R_CUST_INVOICE_TRANS$SALES_PRICE = as.numeric(R_CUST_INVOICE_TRANS$SALES_PRICE)

#R_CUSTOMER_INVOICE_JOURNAL
R_CUSTOMER_INVOICE_JOURNAL$INVOICE_DATE = as.Date(R_CUSTOMER_INVOICE_JOURNAL$INVOICE_DATE,format='%Y-%m-%d')
R_CUSTOMER_INVOICE_JOURNAL$INVOICE_AMOUNT = as.numeric(R_CUSTOMER_INVOICE_JOURNAL$INVOICE_AMOUNT)
R_CUSTOMER_INVOICE_JOURNAL$CASH_DIS_VALUE = as.numeric(R_CUSTOMER_INVOICE_JOURNAL$CASH_DIS_VALUE)
R_CUSTOMER_INVOICE_JOURNAL$LINE_DISCOUNT = as.numeric(R_CUSTOMER_INVOICE_JOURNAL$LINE_DISCOUNT)
R_CUSTOMER_INVOICE_JOURNAL$SALES_SUBTOTAL_AMOUNT = as.numeric(R_CUSTOMER_INVOICE_JOURNAL$SALES_SUBTOTAL_AMOUNT)
R_CUSTOMER_INVOICE_JOURNAL$INVOICE_AMOUNT_AC = as.numeric(R_CUSTOMER_INVOICE_JOURNAL$INVOICE_AMOUNT_AC)
R_CUSTOMER_INVOICE_JOURNAL$LINE_DISCOUNT_AC = as.numeric(R_CUSTOMER_INVOICE_JOURNAL$LINE_DISCOUNT_AC)
R_CUSTOMER_INVOICE_JOURNAL$SALES_SUBTOTAL_AMOUNT_AC = as.numeric(R_CUSTOMER_INVOICE_JOURNAL$SALES_SUBTOTAL_AMOUNT_AC)
R_CUSTOMER_INVOICE_JOURNAL$CHARGES_AC = as.numeric(R_CUSTOMER_INVOICE_JOURNAL$CHARGES_AC)
R_CUSTOMER_INVOICE_JOURNAL$CHARGES = as.numeric(R_CUSTOMER_INVOICE_JOURNAL$CHARGES)

#R_CUSTOMER_TABLE_FINAL
R_CUSTOMER_TABLE_FINAL$CUR_CREDIT_LIMIT = as.numeric(R_CUSTOMER_TABLE_FINAL$CUR_CREDIT_LIMIT)
R_CUSTOMER_TABLE_FINAL$CREDIT_LIMIT = as.numeric(R_CUSTOMER_TABLE_FINAL$CREDIT_LIMIT)

#Remove ROANZ and CONZL from the invoice journal
R_CUSTOMER_INVOICE_JOURNAL <- R_CUSTOMER_INVOICE_JOURNAL[R_CUSTOMER_INVOICE_JOURNAL$DEPARTMENT != 'CONZL',]
R_CUSTOMER_INVOICE_JOURNAL <- R_CUSTOMER_INVOICE_JOURNAL[R_CUSTOMER_INVOICE_JOURNAL$DEPARTMENT != 'ROANZ',]

#Create Year,month and day columns in CUSTOMER INVOICE JOURNAL
R_CUSTOMER_INVOICE_JOURNAL <- transform(R_CUSTOMER_INVOICE_JOURNAL,YEAR_INVOICE=year(INVOICE_DATE),MONTH_INVOICE=month(INVOICE_DATE))

#Tag free text journal entries as 1 and everything else as 0
R_CUSTOMER_INVOICE_JOURNAL$JOURNAL_TF <- ifelse(R_CUSTOMER_INVOICE_JOURNAL$ORDER_TYPE == 'Journal',1, 0)

#Split the INVOICE JOURNALdataframe so free text journal entries have its own dataframe
INVOICE_JOURNAL_TABLE_LIST <- split(R_CUSTOMER_INVOICE_JOURNAL, R_CUSTOMER_INVOICE_JOURNAL$JOURNAL_TF)
R_CUSTOMER_INVOICE_JOURNAL <- INVOICE_JOURNAL_TABLE_LIST[[1]]
R_CUSTOMER_FREE_TEXT_INVOICE_JOURNAL <- INVOICE_JOURNAL_TABLE_LIST[[2]] 
rm(INVOICE_JOURNAL_TABLE_LIST)



#Split the CUSTOMER INVOICE TRANS DATA FRAME SO FREIGHT CHARGES ARE IN A SEPARATE TABLE
R_CUST_INVOICE_TRANS$FREIGHT_TF <- ifelse(R_CUST_INVOICE_TRANS$STYLE_NAME == 'Freight Charged',1, 0)
INVOICE_TRANS_TABLE_LIST <- split(R_CUST_INVOICE_TRANS, R_CUST_INVOICE_TRANS$FREIGHT_TF)
R_CUST_INVOICE_TRANS <- INVOICE_TRANS_TABLE_LIST[[1]]
FREIGHT_CHARGE_TRANS <- INVOICE_TRANS_TABLE_LIST[[2]] 
rm(INVOICE_TRANS_TABLE_LIST)

#Count the number of line items per invoice
R_CUST_INVOICE_TRANS_COUNT <- as.data.frame(table(R_CUST_INVOICE_TRANS$SALES_ID))
colnames(R_CUST_INVOICE_TRANS_COUNT) <- c("SALES_ORDER_NUMBER", "SALES_ORDER_LINE_NUMBER_COUNT")

#Sum quantity and COGs per invoice in the Invoice trans table
R_CUST_INVOICE_TRANS_SUM <- ddply(R_CUST_INVOICE_TRANS,"DOCUMENT_NUMBER__INVOICE_ID_",summarise,INVOICE_QUANTITY = sum(INVOICED_QTY, na.rm=TRUE),COGS2=sum(-1*COGS, na.rm=TRUE))

#Summarise the freight line trans by invoice number
FREIGHT_CHARGE_TRANS <- ddply(FREIGHT_CHARGE_TRANS,"DOCUMENT_NUMBER__INVOICE_ID_", summarise,FREIGHT_REVENUE= sum(LINE_AMT_POST_DISCOUNT,na.rm=TRUE))

#Join the quantity and COGS columns to the CUSTOMER_INVOICE_JOURNAL
R_CUSTOMER_INVOICE_JOURNAL <- merge(R_CUSTOMER_INVOICE_JOURNAL,R_CUST_INVOICE_TRANS_SUM,by.x="INVOICE_NUMBER",by.y="DOCUMENT_NUMBER__INVOICE_ID_",all.x=TRUE,all.y=FALSE)
#Join the freight line item charges to CUSTOMER INVOICE JOURNAL
R_CUSTOMER_INVOICE_JOURNAL <- merge(R_CUSTOMER_INVOICE_JOURNAL,FREIGHT_CHARGE_TRANS,by.x="INVOICE_NUMBER",by.y="DOCUMENT_NUMBER__INVOICE_ID_",all.x=TRUE,all.y=FALSE)
#Join the line items count to the CUSTOMER_INVOICE_JOURNAL
R_CUSTOMER_INVOICE_JOURNAL <- merge(R_CUSTOMER_INVOICE_JOURNAL,R_CUST_INVOICE_TRANS_COUNT,by.x="SALES_ORDER",by.y="SALES_ORDER_NUMBER",all.x=TRUE,all.y=FALSE)


#Join VAS and EDI codes to the customer invoice journal
R_CUSTOMER_INVOICE_JOURNAL <- merge(R_CUSTOMER_INVOICE_JOURNAL,R_CUSTOMER_TABLE_FINAL[,c("CUSTOMER_ACCOUNT","VAS_CODES_GROUP","EDI_CODE")],by="CUSTOMER_ACCOUNT",all.x=TRUE,all.y=FALSE)

# Merge the warehousing cost per units depending on department
R_CUSTOMER_INVOICE_JOURNAL <- merge(R_CUSTOMER_INVOICE_JOURNAL,R_WAREHOUSING_COSTS,by.x="DEPARTMENT",by.y="REGION",all.x=TRUE,all.y=FALSE)

#Add warehousing, SO processing, IT and freight costs to invoice journal using the warehousing costs table PU prices.

#Create inventory management and freight cost columns for sales orders
R_CUSTOMER_INVOICE_JOURNAL <- transform(R_CUSTOMER_INVOICE_JOURNAL,FREIGHT_COST= ifelse(R_CUSTOMER_INVOICE_JOURNAL$ORDER_TYPE == 'Sales order',R_CUSTOMER_INVOICE_JOURNAL$FREIGHT_COSTS_PU*INVOICE_QUANTITY,0),
                                        PICKING_COST= ifelse(R_CUSTOMER_INVOICE_JOURNAL$ORDER_TYPE == 'Sales order',R_CUSTOMER_INVOICE_JOURNAL$PICKING_PU*INVOICE_QUANTITY,0),
                                        GENERAL_DISPATCH_COSTS=ifelse(R_CUSTOMER_INVOICE_JOURNAL$ORDER_TYPE == 'Sales order',R_CUSTOMER_INVOICE_JOURNAL$DISPATCH_PU*INVOICE_QUANTITY,0),
                                        STORAGE_COSTS=ifelse(R_CUSTOMER_INVOICE_JOURNAL$ORDER_TYPE == 'Sales order',R_CUSTOMER_INVOICE_JOURNAL$WAREHOUSING_COSTS_PU*INVOICE_QUANTITY,0),
                                        VAS_COSTS = ifelse(!is.na(R_CUSTOMER_INVOICE_JOURNAL$VAS_CODES_GROUP) & R_CUSTOMER_INVOICE_JOURNAL$ORDER_TYPE == 'Sales order',R_CUSTOMER_INVOICE_JOURNAL$VAS_PU*INVOICE_QUANTITY,0),
                                        PACKAGING_CHARGE=ifelse(R_CUSTOMER_INVOICE_JOURNAL$ORDER_TYPE == 'Sales order',R_CUSTOMER_INVOICE_JOURNAL$PACKAGING_PU*INVOICE_QUANTITY,0))



#Create return reason categories column
R_CUSTOMER_INVOICE_JOURNAL <- left_join(R_CUSTOMER_INVOICE_JOURNAL,R_RETURN_REASON_CODES[,c("RETURN_REASON_CODE","RETURN_REASON_CODE_GROUP")],by='RETURN_REASON_CODE')

#Create inventory management and freight cost columns for return orders
R_CUSTOMER_INVOICE_JOURNAL <- transform(R_CUSTOMER_INVOICE_JOURNAL,
                                        RETURNED_WAREHOUSE_COST = ifelse(R_CUSTOMER_INVOICE_JOURNAL$ORDER_TYPE == 'Returned order' & R_CUSTOMER_INVOICE_JOURNAL$RETURN_REASON_CODE_GROUP != "OM ISSUE",R_CUSTOMER_INVOICE_JOURNAL$RETURNS_PU*INVOICE_QUANTITY,0))

#Create Customer service sales order processing cost column
R_CUSTOMER_INVOICE_JOURNAL <- transform(R_CUSTOMER_INVOICE_JOURNAL,CUSTOMER_SALES_ORDER_PROCESS = 
                                          ifelse(R_CUSTOMER_INVOICE_JOURNAL$ORDER_TYPE == 'Sales order' & !duplicated(R_CUSTOMER_INVOICE_JOURNAL$SALES_ORDER),
                                                 ifelse(!is.na(R_CUSTOMER_INVOICE_JOURNAL$EDI_CODE), 0.083*R_CUSTOMER_INVOICE_JOURNAL$SALES_ORDER_PROCESSING_PH, 0.5*R_CUSTOMER_INVOICE_JOURNAL$SALES_ORDER_PROCESSING_PH),0))
#Create Customer service return order processing cost column
R_CUSTOMER_INVOICE_JOURNAL <- transform(R_CUSTOMER_INVOICE_JOURNAL,CUSTOMER_RETURN_ORDER_PROCESS = 
                                          ifelse(R_CUSTOMER_INVOICE_JOURNAL$ORDER_TYPE == 'Returned order' &!duplicated(R_CUSTOMER_INVOICE_JOURNAL$SALES_ORDER),
                                                 ifelse(R_CUSTOMER_INVOICE_JOURNAL$SALES_ORDER_LINE_NUMBER_COUNT > 10,0.33*R_CUSTOMER_INVOICE_JOURNAL$RETURN_ORDER_PROCESSING_PH,R_CUSTOMER_INVOICE_JOURNAL$RETURN_ORDER_PROCESSING_PH*0.083),0))

#Create IT (per transaction) cost column and fixed cost column
R_CUSTOMER_INVOICE_JOURNAL <- transform(R_CUSTOMER_INVOICE_JOURNAL, 
                              IT_COST_TRANS = 
                              ifelse(R_CUSTOMER_INVOICE_JOURNAL$ORDER_TYPE == 'Sales order' & !is.na(EDI_CODE) & !duplicated(R_CUSTOMER_INVOICE_JOURNAL$SALES_ORDER),R_CUSTOMER_INVOICE_JOURNAL$EDI_TRANSACTION_COSTS,0),
                              IT_COST_FIXED_CS=
                              ifelse(R_CUSTOMER_INVOICE_JOURNAL$ORDER_TYPE == 'Sales order' & !duplicated(R_CUSTOMER_INVOICE_JOURNAL$SALES_ORDER) & grepl("CS",R_CUSTOMER_INVOICE_JOURNAL$EDI_CODE),R_CUSTOMER_INVOICE_JOURNAL$CS_FIXED_COST,0),
                              IT_COST_FIXED_3P5=
                              ifelse(R_CUSTOMER_INVOICE_JOURNAL$ORDER_TYPE == 'Sales order' & !duplicated(R_CUSTOMER_INVOICE_JOURNAL$SALES_ORDER) & grepl("3P5",R_CUSTOMER_INVOICE_JOURNAL$EDI_CODE),R_CUSTOMER_INVOICE_JOURNAL$THREE_P_FIVE_FIXED_COST,0))

#Remove the PU costs from Invoice Journal table
#rm(R_CUSTOMER_INVOICE_JOURNAL$CS_FIXED_COST,R_CUSTOMER_INVOICE_JOURNAL$THREE_P_FIVE_FIXED_COSTS,R_CUSTOMER_INVOICE_JOURNAL$EDI_TRANSACTION_COSTS,R_CUSTOMER_INVOICE_JOURNAL$RETURN_ORDER_PROCESSING_PH,R_CUSTOMER_INVOICE_JOURNAL$SALES_ORDER_PROCESSING_PH,R_CUSTOMER_INVOICE_JOURNAL$RETURNS_PU,R_CUSTOMER_INVOICE_JOURNAL$FREIGHT_COSTS_PU,R_CUSTOMER_INVOICE_JOURNAL$PICKING_PU,R_CUSTOMER_INVOICE_JOURNAL$DISPATCH_PU,R_CUSTOMER_INVOICE_JOURNAL$WAREHOUSING_COSTS_PU,R_CUSTOMER_INVOICE_JOURNAL$VAS_PU,R_CUSTOMER_INVOICE_JOURNAL$PACKAGING_PU)

#Make Line discount a negative as it is an expense
R_CUSTOMER_INVOICE_JOURNAL <- transform(R_CUSTOMER_INVOICE_JOURNAL, LINE_DISCOUNT_AC=-1*LINE_DISCOUNT_AC)
                                       
# New version of length which can handle NA's: if na.rm==T, don't count them
length2 <- function (x, na.rm=TRUE) {
  if (na.rm) sum(!is.na(x))
  else       length(x)
}
#Create sums of numeric values from invoice table by customer_account including counts of invoices and sales orders
#INVOICE_SUMS <- ddply(R_CUSTOMER_INVOICE_JOURNAL,.(YEAR_INVOICE, MONTH_INVOICE, CUSTOMER_ACCOUNT),summarise,
INVOICE_SUMS <- ddply(R_CUSTOMER_INVOICE_JOURNAL,"CUSTOMER_ACCOUNT",summarise,                   
                      #Sales and expenses summed
                      SALES_SUBTOTAL_AMOUNT_AC = sum(SALES_SUBTOTAL_AMOUNT_AC, na.rm=TRUE),
                      LINE_DISCOUNT_AC=sum(LINE_DISCOUNT_AC, na.rm=TRUE),
                      CHARGES_AC = sum(CHARGES_AC, na.rm=TRUE),
                      COGS=sum(COGS2, na.rm=TRUE),
                      FREIGHT_REVENUE = sum(FREIGHT_REVENUE,na.rm=TRUE),
                      FREIGHT_COST=sum(FREIGHT_COST,na.rm=TRUE),
                      PICKING_COST=sum(PICKING_COST,na.rm=TRUE),
                      GENERAL_DISPATCH_COSTS = sum(GENERAL_DISPATCH_COSTS,na.rm=TRUE),
                      STORAGE_COSTS=sum(STORAGE_COSTS,na.rm=TRUE),
                      VAS_COSTS=sum(VAS_COSTS,na.rm=TRUE),
                      PACKAGING_CHARGE=sum(PACKAGING_CHARGE,na.rm=TRUE),
                      RETURNED_WAREHOUSE_COST=sum(RETURNED_WAREHOUSE_COST,na.rm=TRUE),
                      CUSTOMER_SALES_ORDER_PROCESS=sum(CUSTOMER_SALES_ORDER_PROCESS,na.rm=TRUE),
                      CUSTOMER_RETURN_ORDER_PROCESS=sum(CUSTOMER_RETURN_ORDER_PROCESS,na.rm=TRUE),
                      IT_COST_TRANS=sum(IT_COST_TRANS,na.rm=TRUE),
                      IT_COST_FIXED_CS=sum(IT_COST_FIXED_CS,na.rm=TRUE),
                      IT_COST_FIXED_3P5=sum(IT_COST_FIXED_3P5,na.rm=TRUE),
                      
                      #Count what type of returns are made by each customer
                      CARR_ISSUE=length2(which(RETURN_REASON_CODE_GROUP=='CARR ISSUE')),
                      OM_ISSUE=length2(which(RETURN_REASON_CODE_GROUP=='OM ISSUE')),
                      CNSM_CHOIC=length2(which(RETURN_REASON_CODE_GROUP=='CNSM CHOIC')),
                      SALE_ISSUE=length2(which(RETURN_REASON_CODE_GROUP=='SALE ISSUE')),
                      OTHER=length2(which(RETURN_REASON_CODE_GROUP=='OTHER')),
                      CUST_FAULT=length2(which(RETURN_REASON_CODE_GROUP=='CUST FAULT')),
                      WH_ISSUE=length2(which(RETURN_REASON_CODE_GROUP=='WH ISSUE')),
                      DES_FAULT=length2(which(RETURN_REASON_CODE_GROUP=='DES FAULT')),
                      FAB_FAULT=length2(which(RETURN_REASON_CODE_GROUP=='FAB FAULT')),
                      MFG_FAULT=length2(which(RETURN_REASON_CODE_GROUP=='MFG FAULT')),
                      PACK_FAULT=length2(which(RETURN_REASON_CODE_GROUP=='PACK FAULT')),
                      PROD_ISSUE=length2(which(RETURN_REASON_CODE_GROUP=='PROD ISSUE')),
                      
                      #Count different types of invoices raised by each customer
                      SALES_ORDERS = length2(which(ORDER_TYPE=='Sales order' & !duplicated(SALES_ORDER))),
                      RETURN_ORDERS = length2(which(ORDER_TYPE=='Returned order' & !duplicated(SALES_ORDER))),
                      INVOICE_SALES=length2(which(ORDER_TYPE=='Sales order')),
                      INVOICE_RETURNED=length2(which(ORDER_TYPE=='Returned order')),
                      ATONCE=length2(which(ORDERTYPE2=='AtOnce' & ORDER_TYPE=='Sales order' & !duplicated(SALES_ORDER))),
                      PROMO=length2(which(ORDERTYPE2=='Promo' & ORDER_TYPE=='Sales order' & !duplicated(SALES_ORDER))),
                      INDENT=length2(which(ORDERTYPE2=='Indent' & ORDER_TYPE=='Sales order' & !duplicated(SALES_ORDER))),
                      EOL=length2(which(ORDERTYPE2== 'EOL' & ORDER_TYPE=='Sales order' & !duplicated(SALES_ORDER))),
                      INDENT_RETURNS=length2(which(ORDERTYPE2=='Indent' & ORDER_TYPE=='Returned order' & !duplicated(SALES_ORDER)))) 
                      

#Add fixed cost IT costs
#R_CUSTOMER_TABLE_FINAL <- transform(R_CUSTOMER_TABLE_FINAL,IT_FIXED_COST = 
 #                                     ifelse(R_CUSTOMER_TABLE_FINAL$EDI_CODE == 'ANZCS',-13215/length(which(R_CUSTOMER_TABLE_FINAL$EDI_CODE =='ANZCS')),
  #                                           ifelse(R_CUSTOMER_TABLE_FINAL$EDI_CODE == 'NZL3P5' | R_CUSTOMER_TABLE_FINAL$EDI_CODE =='AUS3P5',-9575/length(which(R_CUSTOMER_TABLE_FINAL$EDI_CODE =='NZL3P5' | R_CUSTOMER_TABLE_FINAL$EDI_CODE =='AUS3P5')),0)))

#Add those counts/sums created in INVOICE SUMS to the customer table
R_CUSTOMER_TABLE_FINAL <- merge(INVOICE_SUMS,R_CUSTOMER_TABLE_FINAL,by="CUSTOMER_ACCOUNT",all.x=TRUE,all.y=FALSE)

#Add the free text invoices into the customer level view
R_CUSTOMER_FREE_TEXT_INVOICE_JOURNAL <- transform(R_CUSTOMER_FREE_TEXT_INVOICE_JOURNAL,MONTH_INVOICE=month(INVOICE_DATE),YEAR_INVOICE=year(INVOICE_DATE))
#R_CUSTOMER_FREE_TEXT_INVOICE_JOURNAL_SUMS <- ddply(R_CUSTOMER_FREE_TEXT_INVOICE_JOURNAL,.(YEAR_INVOICE,MONTH_INVOICE,CUSTOMER_ACCOUNT),summarise,MANUAL_DISCOUNT = sum(SALES_SUBTOTAL_AMOUNT_AC))
R_CUSTOMER_FREE_TEXT_INVOICE_JOURNAL_SUMS <- ddply(R_CUSTOMER_FREE_TEXT_INVOICE_JOURNAL,"CUSTOMER_ACCOUNT",summarise,MANUAL_DISCOUNT = sum(SALES_SUBTOTAL_AMOUNT_AC))
#R_CUSTOMER_TABLE_FINAL <- merge(R_CUSTOMER_TABLE_FINAL,R_CUSTOMER_FREE_TEXT_INVOICE_JOURNAL_SUMS,by=c("YEAR_INVOICE", "MONTH_INVOICE","CUSTOMER_ACCOUNT"),all.x=TRUE,all.y=TRUE)
R_CUSTOMER_TABLE_FINAL <- merge(R_CUSTOMER_TABLE_FINAL,R_CUSTOMER_FREE_TEXT_INVOICE_JOURNAL_SUMS,by="CUSTOMER_ACCOUNT",all.x=TRUE,all.y=TRUE)

#Create the different levels of profitability
#Gross Sales
R_CUSTOMER_TABLE_FINAL <- transform(R_CUSTOMER_TABLE_FINAL, GROSS_SALES = rowSums(R_CUSTOMER_TABLE_FINAL[, c("SALES_SUBTOTAL_AMOUNT_AC", "LINE_DISCOUNT_AC")],na.rm=TRUE))

#Net Sales
R_CUSTOMER_TABLE_FINAL <- transform(R_CUSTOMER_TABLE_FINAL, NET_SALES = rowSums(R_CUSTOMER_TABLE_FINAL[, c("SALES_SUBTOTAL_AMOUNT_AC", "MANUAL_DISCOUNT")],na.rm=TRUE))

#Gross Margin
R_CUSTOMER_TABLE_FINAL <- transform(R_CUSTOMER_TABLE_FINAL, GROSS_MARGIN = rowSums(R_CUSTOMER_TABLE_FINAL[, c("NET_SALES", "COGS")],na.rm=TRUE))

#Gross Profit
R_CUSTOMER_TABLE_FINAL <- transform(R_CUSTOMER_TABLE_FINAL, GROSS_PROFIT = rowSums(R_CUSTOMER_TABLE_FINAL[, c("GROSS_MARGIN","CHARGES_AC","FREIGHT_REVENUE","FREIGHT_COST","PICKING_COST","GENERAL_DISPATCH_COSTS","STORAGE_COSTS","VAS_COSTS","PACKAGING_CHARGE","RETURNED_WAREHOUSE_COST")],na.rm=TRUE))

#Profit
R_CUSTOMER_TABLE_FINAL <- transform(R_CUSTOMER_TABLE_FINAL, PROFIT = rowSums(R_CUSTOMER_TABLE_FINAL[, c("GROSS_PROFIT", "CUSTOMER_SALES_ORDER_PROCESS","CUSTOMER_RETURN_ORDER_PROCESS","IT_COST_TRANS","IT_COST_FIXED_CS","IT_COST_FIXED_3P5")],na.rm=TRUE))

#Profit % of Gross sales
R_CUSTOMER_TABLE_FINAL <- transform(R_CUSTOMER_TABLE_FINAL, PROFIT_PERCENT = R_CUSTOMER_TABLE_FINAL$PROFIT*100/R_CUSTOMER_TABLE_FINAL$GROSS_SALES)








